name: CD-FRONTEND

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - 'feature/**'
  # pull_request:
  #   branches:
  #     - 'feature/**'

jobs:
  deploy-frontend-pre:
    uses: Guistarcks/workflow-reutilizable-demo/.github/workflows/test-unitarios.yml@main
    with:
      node-version: '18.x'
      
  deploy-frontend-prod:
    uses: Guistarcks/workflow-reutilizable-demo/.github/workflows/test-unitarios.yml@main
    with:
      node-version: '18.x'

