name: CD-BACKEND

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  deploy-backend-pre:
    uses: Guistarcks/workflow-reutilizable-demo/.github/workflows/test-unitarios.yml@main
    with:
      node-version: '18.x'
   
  deploy-backend-prod:
    uses: Guistarcks/workflow-reutilizable-demo/.github/workflows/test-unitarios.yml@main
    with:
      node-version: '18.x'
  


