name: CI-FRONTEND

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - 'feature/**'
  # pull_request:
  #   branches:
  #     - 'feature/**'

jobs:
  test-frontend:
    uses: Guistarcks/workflow-reutilizable-demo/.github/workflows/test-unitarios.yml@main
    with:
      node-version: '18.x'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


