name: CI-FRONTEND #${{ github.run_number }}

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'
    paths:
      - 'frontend/**'
  pull_request:
    types: [closed]
    branches:
      - 'develop'
    paths:
      - 'frontend/**'

jobs:
  test-frontend:
    uses: Guistarcks/workflow-reutilizable-demo/.github/workflows/test-unitarios.yml@main
    with:
      node-version: '18.x'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


