name: CI-BACKEND

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - 'feature/**'
  # pull_request:
  #   branches:
  #     - 'feature/**'

jobs:
  test-backend:
    uses: Guistarcks/workflow-reutilizable-demo/.github/workflows/test-unitarios.yml@main
    with:
      node-version: '18.x'


 